version: '3.1'

services:

  maxwell-state:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: maxwell
    ports:
      - 4406:3306

